services:
  mongodb:
    image: mongo:latest
    container_name: n-mongo-prod-mongodb-1
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
    mem_limit: 2g
    mem_reservation: 512m

volumes:
  mongo-data:
